# For more info on HTTP files go to https://aka.ms/vs/httpfile
@Web_HostAddress = https://localhost:5001

###

# GET Games
GET {{Web_HostAddress}}/api/Games

###

# POST Games
POST {{Web_HostAddress}}/api/Games
Content-Type: application/json

// CreateGameCommand
{
  "Winner": "Winner",
  "Opponent": "Opponent"
}